export default [
    {
        pic: '/pop1-california.webp',
        place: 'California',
        country: 'United States of America',
        reviews: '20 Reviews',
        days: '2 Days',
        price: '$1500',
    },
    {
        pic: '/pop2-bohol.webp',
        place: 'Bohol Sea',
        country: 'Philippines',
        reviews: '17 Reviews',
        days: '7 Days',
        price: '$2000',
    },
    {
        pic: '/pop3-london.webp',
        place: 'London',
        country: 'United Kingdom',
        reviews: '26 Reviews',
        days: '4 Days',
        price: '$2500',
    },
    {
        pic: '/pop4-miami.webp',
        place: 'Miami Beach',
        country: 'United States of America',
        reviews: '60 Reviews',
        days: '2 Days',
        price: '$2500',
    },
    {
        pic: '/pop5-cinque.webp',
        place: 'Cinque Terre National Park',
        country: 'Italy',
        reviews: '20 Reviews',
        days: '3 Days',
        price: '$3000',
    },
    {
        pic: '/pop6-saintmartin.webp',
        place: 'Saintmartin Island',
        country: 'United States of America',
        reviews: '10 Reviews',
        days: '2 Days',
        price: '$1500',
    },
]